### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Abizern** [danielctull/DCTConnectionController#1]
I'm getting Errors for 

**DCTConnectionController.m**

```
#import "NSMutableSet+DCTExtras.h"
```

**DCTConnectionQueue.m**

```
#import "NSObject+DCTKVOExtras.h
```

**Comment by danielctull** [comment]
You also need [DCTFoundation](https://github.com/danielctull/DCTFoundation) in your project, this should be listed in the read me and/or documentation. :)
